apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: keyvault-sql
  namespace: api
spec:
  provider: azure
  parameters:
    keyvaultName: "sqlinfo"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "3b922360-6604-469e-8b51-7b532c1387d9"
    objects:  |
      array:
        - |
          objectName: SQLSERVER
          objectAlias: SQL_SERVER
          objectType: secret
        - |
          objectName: SQLDBNAME
          objectAlias: SQL_DBNAME
          objectType: secret
        - |
          objectName: SQLUSER
          objectAlias: SQL_USER
          objectType: secret
        - |
          objectName: SQLPASSWORD
          objectAlias: SQL_PASSWORD
          objectType: secret        
    tenantId: "c3d35eac-b32d-46b8-b319-22c470b880d4"
