apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  SQL_SERVER: sqlserverxzq2360.database.windows.net
  SQL_USER: sqladminxZq2360
  SQL_PASSWORD: qD1qx7Sh8
  SQL_DBNAME: mydrivingDB