apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: api
type: Opaque
data:
  SQL_SERVER: c3Fsc2VydmVyeHpxMjM2MC5kYXRhYmFzZS53aW5kb3dzLm5ldAo=
  SQL_USER: c3FsYWRtaW54WnEyMzYwCg==
  SQL_PASSWORD: cUQxcXg3U2g4Cg==
  SQL_DBNAME: bXlkcml2aW5nREIK